disabled_rules: # rule identifiers turned on by default to exclude from running
- function_parameter_count
- notification_center_detachment
- trailing_whitespace

identifier_name:
  min_length: 3 # only error
  excluded: # excluded via string array
    - id
    - x
    - y

line_length: 150
